/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package info.nehrke;

import org.junit.Test;

public class LambdaTest {
    @Test public void testAppHasAGreeting() {
        Lambda classUnderTest = new Lambda();
    }
}
